### ISSUE TITLE
USBCAN 4EU设备打开失败

### ISSUE THREAD

**Issue by xzhlksh** [123zmz123/ZlgCanDriver#1]
如题，首先修改276行的bug：
https://github.com/123zmz123/ZlgCanDriver/blob/7ff1e80b6105967ff17d3f6e0627132e63ab089e/ZLGCanControl.py#L276
这里把VCI_USBCAN_E_U改成VCI_USBCAN_4E_U

然后用open_new函数打开设备还是失败，自己加了个ReadErrInfo函数读取错误码。读到的错误码是0x8000，查手册是内存不足？这个可能原因会是什么？
我这里用cpp调dll完全没问题，ZCANPro也能正常打开设备。

**Comment by 123zmz123** [comment]
谢谢指正，我之前调试过USB-CAN-4EU，没用python，但我记得当时更新了下dll，好像老版本的dll不太支持，你用cpp 是在调用 该项目自带的dll吗？
另外请参考下官方手册，4eu配置和2eu有所区别，您可以更改下代码。

**Comment by xzhlksh** [comment]
> 谢谢指正，我之前调试过USB-CAN-4EU，没用python，但我记得当时更新了下dll，好像老版本的dll不太支持，你用cpp 是在调用 该项目自带的dll吗？
> 另外请参考下官方手册，4eu配置和2eu有所区别，您可以更改下代码。

多谢提醒，我想起来了前年给周立功工程师反馈过x64 dll调用的bug，然后就在自己的cpp工程里随手改了。没想到最近下载新版canlib库里，官方还是没修。。。
解决方法是把4eu驱动包里x64的dll复制到\kerneldlls 文件夹下，然后把kerneldll.ini里31对应的dll改成x64版本dll文件名。估摸着其他型号的卡也会有类似问题。
这个issue可以关了，非常感谢您做的python封装

**Comment by 123zmz123** [comment]
好的
